services:

  db-ms-user:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: db-ms-user
      POSTGRES_USER: ${USER_DB_USERNAME}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - microservices-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER_DB_USERNAME} -d db-ms-user" ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  user-db-data:

networks:
  microservices-network:
    driver: bridge